repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff
        language_version: python3
        args: ["--fix"]
        exclude: ^(migrations/|alembic/|__pycache__/|\.venv/)

  - repo: local
    hooks:
      - id: alembic-check-multiple-heads
        name: Alembic – prevent multiple heads
        entry: bash -c 'alembic heads | grep "head" | wc -l | xargs test 1 -eq'
        language: system
        pass_filenames: false
        types: [python]
