"""
Mapping of domain exception error codes to HTTP status codes.
"""

from fastapi import status

ERROR_STATUS_MAP = {
    # Authentication & Authorization
    "UNAUTHORIZED": status.HTTP_401_UNAUTHORIZED,
    "INVALID_TOKEN": status.HTTP_401_UNAUTHORIZED,
    "TOKEN_EXPIRED": status.HTTP_401_UNAUTHORIZED,
    "AUTHENTICATION_ERROR": status.HTTP_401_UNAUTHORIZED,
    "INVALID_CREDENTIALS": status.HTTP_401_UNAUTHORIZED,
    "FORBIDDEN": status.HTTP_403_FORBIDDEN,
    "PERMISSION_DENIED": status.HTTP_403_FORBIDDEN,
    "ACCOUNT_INACTIVE": status.HTTP_403_FORBIDDEN,
    "ACCOUNT_PENDING_APPROVAL": status.HTTP_403_FORBIDDEN,
    "ACCOUNT_UNVERIFIED": status.HTTP_403_FORBIDDEN,
    "ACCOUNT_LOCKED": status.HTTP_429_TOO_MANY_REQUESTS,
    "TOO_MANY_ATTEMPTS": status.HTTP_429_TOO_MANY_REQUESTS,
    "USER_NOT_IN_ORGANIZATION": status.HTTP_403_FORBIDDEN,
    # Validation & Input Errors
    "VALIDATION_ERROR": status.HTTP_422_UNPROCESSABLE_ENTITY,
    "INVALID_INPUT": status.HTTP_422_UNPROCESSABLE_ENTITY,
    "INVALID_SUGGESTION_DATA": status.HTTP_400_BAD_REQUEST,
    "BAD_REQUEST": status.HTTP_400_BAD_REQUEST,
    "CLOSED_TICKET": status.HTTP_400_BAD_REQUEST,
    "INVALID_OTP": status.HTTP_400_BAD_REQUEST,
    "INVALID_RESET_CODE": status.HTTP_400_BAD_REQUEST,
    "RESET_TOKEN_EXPIRED": status.HTTP_400_BAD_REQUEST,
    "PASSWORD_REUSE_ERROR": status.HTTP_400_BAD_REQUEST,
    "INVALID_FILE_TYPE": status.HTTP_400_BAD_REQUEST,
    "FILE_TOO_LARGE": status.HTTP_400_BAD_REQUEST,
    "NO_FIELDS_TO_UPDATE": status.HTTP_400_BAD_REQUEST,
    # Resource Errors
    "NOT_FOUND": status.HTTP_404_NOT_FOUND,
    "SOURCE_NOT_FOUND": status.HTTP_404_NOT_FOUND,
    "RESOURCE_NOT_FOUND": status.HTTP_404_NOT_FOUND,
    # Conflict & Duplicate Errors
    "EMAIL_ALREADY_EXISTS": status.HTTP_409_CONFLICT,
    "RESOURCE_EXISTS": status.HTTP_409_CONFLICT,
    "DUPLICATE_ENTRY": status.HTTP_409_CONFLICT,
    "DUPLICATE_URL": status.HTTP_409_CONFLICT,
    "USER_ALREADY_REGISTERED": status.HTTP_409_CONFLICT,
    "REGISTRATION_PENDING": status.HTTP_409_CONFLICT,
    "RESOURCE_LOCKED": status.HTTP_423_LOCKED,
    # Rate Limiting
    "RATE_LIMIT_EXCEEDED": status.HTTP_429_TOO_MANY_REQUESTS,
    # Server Errors
    "INTERNAL_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "PROCESSING_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "INTERNAL_SERVER_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "HTTP_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    # Service Availability
    "SERVICE_UNAVAILABLE": status.HTTP_503_SERVICE_UNAVAILABLE,
    "DEPENDENCY_ERROR": status.HTTP_503_SERVICE_UNAVAILABLE,
    "PARALLEL_AI_SEARCH_FAILED": status.HTTP_503_SERVICE_UNAVAILABLE,
    # Timeout
    "TIMEOUT": status.HTTP_504_GATEWAY_TIMEOUT,
    # Method Not Allowed
    "METHOD_NOT_ALLOWED": status.HTTP_405_METHOD_NOT_ALLOWED,
    # OAuth & Authentication Flow
    "OAUTH_FLOW_ERROR": status.HTTP_401_UNAUTHORIZED,
    "OAUTH_STATE_INVALID": status.HTTP_400_BAD_REQUEST,
    "OAUTH_TOKEN_INVALID": status.HTTP_400_BAD_REQUEST,
    "OAUTH_TOKEN_EXCHANGE_FAILED": status.HTTP_401_UNAUTHORIZED,
    "OAUTH_TOKEN_VERIFICATION_FAILED": status.HTTP_401_UNAUTHORIZED,
    "MISSING_ID_TOKEN": status.HTTP_401_UNAUTHORIZED,
    "MISSING_EMAIL": status.HTTP_400_BAD_REQUEST,
    "INVALID_CLIENT": status.HTTP_400_BAD_REQUEST,
    # Scraping Related
    "EXTRACTION_FAILED": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "SOURCE_INACTIVE": status.HTTP_400_BAD_REQUEST,
    "SCRAPE_IN_PROGRESS": status.HTTP_409_CONFLICT,
    "JOB_NOT_FOUND": status.HTTP_404_NOT_FOUND,
    # Billing
    "BILLING_ERROR": status.HTTP_402_PAYMENT_REQUIRED,
    # URL Validation
    "INVALID_URL": status.HTTP_400_BAD_REQUEST,
    "INVALID_DOMAIN": status.HTTP_400_BAD_REQUEST,
    "UNREACHABLE_URL": status.HTTP_400_BAD_REQUEST,
    # HTTP Exception
    "HTTP_EXCEPTION": status.HTTP_500_INTERNAL_SERVER_ERROR,
    # Async & Configuration
    "ASYNC_LOOP_CONFLICT": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "CONFIGURATION_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "NETWORK_ERROR": status.HTTP_503_SERVICE_UNAVAILABLE,
    # Data Revision
    "DATA_REVISION_NOT_FOUND": status.HTTP_404_NOT_FOUND,
    "LLM_USAGE_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "LLM_PROVIDER_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "LLM_QUERY_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "PARALLEL_USAGE_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "PARALLEL_QUERY_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "PARALLEL_PROVIDER_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "DASHBOARD_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "DASHBOARD_OVERVIEW_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "REVENUE_TREND_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "AI_CREDITS_TREND_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "PAYMENT_BREAKDOWN_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "INVALID_DATE_RANGE": status.HTTP_400_BAD_REQUEST,
    "CUSTOMER_NOT_FOUND": status.HTTP_404_NOT_FOUND,
    "INVALID_CUSTOMER_FILTER": status.HTTP_400_BAD_REQUEST,
    "CUSTOMER_DATA_RETRIEVAL_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "CUSTOMER_ACTIVITY_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "PAYMENT_STATUS_ERROR": status.HTTP_400_BAD_REQUEST,
    "CUSTOMER_USAGE_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    # Storage Errors
    "STORAGE_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "STORAGE_CONNECTION_ERROR": status.HTTP_503_SERVICE_UNAVAILABLE,
    "STORAGE_NOT_FOUND": status.HTTP_404_NOT_FOUND,
    # Scraping Errors
    "SCRAPING_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "SCRAPING_TIMEOUT": status.HTTP_504_GATEWAY_TIMEOUT,
    "SCRAPING_CONNECTION_ERROR": status.HTTP_503_SERVICE_UNAVAILABLE,
    "INVALID_SOURCE": status.HTTP_400_BAD_REQUEST,
    "EMPTY_CONTENT": status.HTTP_404_NOT_FOUND,
    # LLM Extraction Errors
    "LLM_EXTRACTION_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "LLM_INVALID_RESPONSE": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "LLM_VALIDATION_ERROR": status.HTTP_422_UNPROCESSABLE_ENTITY,
    "LLM_RATE_LIMIT": status.HTTP_429_TOO_MANY_REQUESTS,
    "LLM_API_ERROR": status.HTTP_502_BAD_GATEWAY,
    "LLM_CONFIGURATION_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    # Parallel Extraction Errors
    "PARALLEL_EXTRACTION_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "PARALLEL_RATE_LIMIT": status.HTTP_429_TOO_MANY_REQUESTS,
    # Metrics Service
    "METRICS_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "REVENUE_METRICS_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "USER_METRICS_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "AI_CREDITS_METRICS_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "PARALLEL_METRICS_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "USER_PAYMENT_STATUS_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    # Scraping Admin
    "SCRAPING_JOB_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "MANUAL_SCRAPE_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "STUCK_JOB_RETRY_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "CLEAR_STUCK_JOBS_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "TASK_INITIATION_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    # Jurisdiction Change Errors
    "CHANGE_ALREADY_ACCEPTED": status.HTTP_409_CONFLICT,
    "CHANGE_ALREADY_HAS_TICKET": status.HTTP_409_CONFLICT,
    "JURISDICTION_CHANGE_NOT_FOUND": status.HTTP_404_NOT_FOUND,
    "JURISDICTION_SCRAPE_JOB_NOT_FOUND": status.HTTP_404_NOT_FOUND,
    # Comment Errors
    "COMMENT_NOT_FOUND": status.HTTP_404_NOT_FOUND,
    "COMMENT_DELETED": status.HTTP_400_BAD_REQUEST,
    "COMMENT_OWNERSHIP_ERROR": status.HTTP_403_FORBIDDEN,
    "INVALID_COMMENT_DATA": status.HTTP_400_BAD_REQUEST,
    "ATTACHMENT_UPLOAD_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    # Image Upload Errors
    "IMAGE_VALIDATION_ERROR": status.HTTP_400_BAD_REQUEST,
    "INVALID_IMAGE_FORMAT": status.HTTP_400_BAD_REQUEST,
    "IMAGE_TOO_LARGE": status.HTTP_400_BAD_REQUEST,
    "TOO_MANY_IMAGES": status.HTTP_400_BAD_REQUEST,
    "GIF_NOT_ALLOWED": status.HTTP_400_BAD_REQUEST,
    # Organization Management Errors
    "ORGANIZATION_DATA_RETRIEVAL_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "ORGANIZATION_EXPORT_ERROR": status.HTTP_500_INTERNAL_SERVER_ERROR,
    "INVALID_ORGANIZATION_FILTER": status.HTTP_400_BAD_REQUEST,
    # Blog Generation
    "BLOG_GENERATION_IN_PROGRESS": status.HTTP_409_CONFLICT,
    "BULK_BLOG_IN_PROGRESS": status.HTTP_409_CONFLICT,
    "EMPTY_JURISDICTION_SET": status.HTTP_400_BAD_REQUEST,
}
