"""Added provider_user_id field to User Model

Revision ID: 00d2075dac2c
Revises: f661a36459ec
Create Date: 2025-11-28 07:03:14.555001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '00d2075dac2c'
down_revision: Union[str, Sequence[str], None] = 'f661a36459ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provider_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_users_provider_user_id'), 'users', ['provider_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_provider_user_id'), table_name='users')
    op.drop_column('users', 'provider_user_id')
    # ### end Alembic commands ###
