"""add country email company_size and org_type to organizations

Revision ID: 09d460509b3b
Revises: ab732ba075d6
Create Date: 2026-01-28 10:55:35.406380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '09d460509b3b'
down_revision: Union[str, Sequence[str], None] = 'ab732ba075d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create ENUM type first
    company_size_enum = sa.Enum(
        'SMALL',
        'MEDIUM',
        'LARGE',
        'XLARGE',
        'ENTERPRISE',
        name='companysize',
    )
    company_size_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'organizations',
        sa.Column(
            'country',
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
    )
    op.add_column(
        'organizations',
        sa.Column(
            'email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
    )
    op.add_column(
        'organizations',
        sa.Column('company_size', company_size_enum, nullable=True),
    )
    op.add_column(
        'organizations',
        sa.Column(
            'org_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'org_type')
    op.drop_column('organizations', 'company_size')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'country')

    # Drop ENUM type
    op.execute('DROP TYPE IF EXISTS companysize')
    # ### end Alembic commands ###
