"""add_jurisdiction_id_to_llm_usage_logs

Revision ID: 0b0e88f773cf
Revises: 5260ea691bff
Create Date: 2026-01-09 20:55:08.424801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0e88f773cf'
down_revision: Union[str, Sequence[str], None] = '5260ea691bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_usage_logs', sa.Column('jurisdiction_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_llm_usage_logs_jurisdiction_id'), 'llm_usage_logs', ['jurisdiction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_usage_logs_jurisdiction_id'), table_name='llm_usage_logs')
    op.drop_column('llm_usage_logs', 'jurisdiction_id')
    # ### end Alembic commands ###
