"""add_llm_usage_and_provider_status_tables

Revision ID: 10bfbf0383bb
Revises: d2cfa17a3670
Create Date: 2025-12-16 01:14:19.998032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10bfbf0383bb'
down_revision: Union[str, Sequence[str], None] = 'd2cfa17a3670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'llm_usage_logs',
        sa.Column(
            'id',
            postgresql.UUID(as_uuid=True),
            nullable=False
        ),
        sa.Column('request_id', sa.String(length=255), nullable=False),
        sa.Column('model', sa.String(length=255), nullable=False),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column(
            'user_id',
            postgresql.UUID(as_uuid=True),
            nullable=True
        ),
        sa.Column(
            'organization_id',
            postgresql.UUID(as_uuid=True),
            nullable=True
        ),
        sa.Column('input_tokens', sa.Integer(), nullable=False),
        sa.Column('output_tokens', sa.Integer(), nullable=False),
        sa.Column('total_tokens', sa.Integer(), nullable=False),
        sa.Column('cost_usd', sa.Float(), nullable=False),
        sa.Column('latency_ms', sa.Float(), nullable=False),
        sa.Column('success', sa.Boolean(), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('endpoint', sa.String(length=255), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False
        ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_llm_usage_logs_model'),
        'llm_usage_logs',
        ['model'],
        unique=False
    )
    op.create_index(
        op.f('ix_llm_usage_logs_organization_id'),
        'llm_usage_logs',
        ['organization_id'],
        unique=False
    )
    op.create_index(
        op.f('ix_llm_usage_logs_provider'),
        'llm_usage_logs',
        ['provider'],
        unique=False
    )
    op.create_index(
        op.f('ix_llm_usage_logs_request_id'),
        'llm_usage_logs',
        ['request_id'],
        unique=False
    )
    op.create_index(
        op.f('ix_llm_usage_logs_user_id'),
        'llm_usage_logs',
        ['user_id'],
        unique=False
    )
    op.create_table(
        'llm_provider_status',
        sa.Column(
            'id',
            postgresql.UUID(as_uuid=True),
            nullable=False
        ),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('model', sa.String(length=255), nullable=True),
        sa.Column('is_available', sa.Boolean(), nullable=False),
        sa.Column('error_rate', sa.Float(), nullable=False),
        sa.Column('avg_latency_ms', sa.Float(), nullable=False),
        sa.Column('requests_last_hour', sa.Integer(), nullable=False),
        sa.Column('rate_limit_remaining', sa.Integer(), nullable=True),
        sa.Column(
            'rate_limit_reset_at',
            sa.DateTime(timezone=True),
            nullable=True
        ),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.Column(
            'last_success_at',
            sa.DateTime(timezone=True),
            nullable=True
        ),
        sa.Column(
            'last_error_at',
            sa.DateTime(timezone=True),
            nullable=True
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False
        ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_llm_provider_status_model'),
        'llm_provider_status',
        ['model'],
        unique=False
    )
    op.create_index(
        op.f('ix_llm_provider_status_provider'),
        'llm_provider_status',
        ['provider'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_llm_provider_status_provider'),
        table_name='llm_provider_status'
    )
    op.drop_index(
        op.f('ix_llm_provider_status_model'),
        table_name='llm_provider_status'
    )
    op.drop_table('llm_provider_status')
    op.drop_index(
        op.f('ix_llm_usage_logs_user_id'),
        table_name='llm_usage_logs'
    )
    op.drop_index(
        op.f('ix_llm_usage_logs_request_id'),
        table_name='llm_usage_logs'
    )
    op.drop_index(
        op.f('ix_llm_usage_logs_provider'),
        table_name='llm_usage_logs'
    )
    op.drop_index(
        op.f('ix_llm_usage_logs_organization_id'),
        table_name='llm_usage_logs'
    )
    op.drop_index(
        op.f('ix_llm_usage_logs_model'),
        table_name='llm_usage_logs'
    )
    op.drop_table('llm_usage_logs')
    # ### end Alembic commands ###
