"""add timeout_at field to scrape_jobs

Revision ID: 122ea317508a
Revises: 83cde4a08354
Create Date: 2025-12-25 19:57:18.237898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '122ea317508a'
down_revision: Union[str, Sequence[str], None] = '83cde4a08354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_jobs', sa.Column('timeout_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_scrape_jobs_timeout_at'), 'scrape_jobs', ['timeout_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrape_jobs_timeout_at'), table_name='scrape_jobs')
    op.drop_column('scrape_jobs', 'timeout_at')
    # ### end Alembic commands ###
