"""add geographic targeting to campaigns

Revision ID: 14f6596c0ae7
Revises: e58d9577b3ac
Create Date: 2026-05-26 12:18:52.043094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14f6596c0ae7'
down_revision: Union[str, Sequence[str], None] = 'e58d9577b3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('target_countries', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('campaigns', sa.Column('target_states', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'target_states')
    op.drop_column('campaigns', 'target_countries')
    # ### end Alembic commands ###
