"""add_jurisdiction_scheduling_and_scrape_jobs

Revision ID: 15738e9d81d0
Revises: c808117ae395
Create Date: 2026-01-09 19:14:01.976709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15738e9d81d0'
down_revision: Union[str, Sequence[str], None] = 'c808117ae395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('data_revisions_source_id_fkey'), 'data_revisions', type_='foreignkey')
    op.create_foreign_key(None, 'data_revisions', 'sources', ['source_id'], ['id'])
    op.drop_index(op.f('ix_field_mappings_source_original'), table_name='field_mappings', if_exists=True)
    op.drop_constraint(op.f('field_mappings_source_id_fkey'), 'field_mappings', type_='foreignkey')
    op.create_foreign_key(None, 'field_mappings', 'sources', ['source_id'], ['id'])
    
    # Create jurisdiction_scrape_jobs table
    op.create_table('jurisdiction_scrape_jobs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('jurisdiction_id', sa.UUID(), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'SCRAPING', 'CONSOLIDATING', 'FILTERING', 'ANALYZING', 'COMPLETED', 'FAILED', name='jurisdictionscrapejobstatus'), nullable=False),
        sa.Column('total_sources', sa.Integer(), nullable=False),
        sa.Column('successful_sources', sa.Integer(), nullable=False),
        sa.Column('filtered_sources', sa.Integer(), nullable=False),
        sa.Column('consolidated_content_key', sa.String(), nullable=True),
        sa.Column('extracted_data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jurisdiction_scrape_jobs_id'), 'jurisdiction_scrape_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jurisdiction_scrape_jobs_jurisdiction_id'), 'jurisdiction_scrape_jobs', ['jurisdiction_id'], unique=False)

    op.add_column('jurisdictions', sa.Column('scrape_frequency', sa.Enum('HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY', name='scrapefrequency'), nullable=True))
    op.add_column('jurisdictions', sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jurisdictions', sa.Column('next_scrape_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jurisdictions', sa.Column('enable_auto_scrape', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('tickets', 'ticket_number',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("nextval('tickets_ticket_number_seq'::regclass)"))
    op.drop_constraint(op.f('uq_tickets_ticket_number'), 'tickets', type_='unique')
    op.create_index(op.f('ix_tickets_ticket_number'), 'tickets', ['ticket_number'], unique=True)
    op.drop_constraint(op.f('tickets_source_id_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'sources', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_source_id_fkey'), 'tickets', 'sources', ['source_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tickets_ticket_number'), table_name='tickets')
    op.create_unique_constraint(op.f('uq_tickets_ticket_number'), 'tickets', ['ticket_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('tickets', 'ticket_number',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("nextval('tickets_ticket_number_seq'::regclass)"))
    op.drop_column('jurisdictions', 'enable_auto_scrape')
    op.drop_column('jurisdictions', 'next_scrape_time')
    op.drop_column('jurisdictions', 'last_scraped_at')
    op.drop_column('jurisdictions', 'scrape_frequency')
    # Drop jurisdiction_scrape_jobs table
    op.drop_index(op.f('ix_jurisdiction_scrape_jobs_jurisdiction_id'), table_name='jurisdiction_scrape_jobs')
    op.drop_index(op.f('ix_jurisdiction_scrape_jobs_id'), table_name='jurisdiction_scrape_jobs')
    op.drop_table('jurisdiction_scrape_jobs')
    
    op.drop_constraint(None, 'field_mappings', type_='foreignkey')
    op.create_foreign_key(op.f('field_mappings_source_id_fkey'), 'field_mappings', 'sources', ['source_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_field_mappings_source_original'), 'field_mappings', ['source_id', 'original_field_name'], unique=False)
    op.drop_constraint(None, 'data_revisions', type_='foreignkey')
    op.create_foreign_key(op.f('data_revisions_source_id_fkey'), 'data_revisions', 'sources', ['source_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###