"""Create data_revisions table

Revision ID: 1ab5a062c90b
Revises: 89a5fbb44821
Create Date: 2025-11-24 01:17:00.814579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1ab5a062c90b'
down_revision: Union[str, Sequence[str], None] = '89a5fbb44821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('minio_object_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('was_change_detected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_revisions_source_id'), 'data_revisions', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_revisions_source_id'), table_name='data_revisions')
    op.drop_table('data_revisions')
    # ### end Alembic commands ###
