"""add_content_hash_to_jurisdiction_scrape_job

Revision ID: 1af7ec7b0800
Revises: 6f6ede66d8df
Create Date: 2026-01-18 23:40:53.142089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1af7ec7b0800'
down_revision: Union[str, Sequence[str], None] = '6f6ede66d8df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jurisdiction_scrape_jobs', sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jurisdiction_scrape_jobs', 'content_hash')
    # ### end Alembic commands ###
