"""add_parallel_usage_tracking

Revision ID: 20dfc5b10985
Revises: 13914474515e
Create Date: 2025-12-19 00:38:13.752435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '20dfc5b10985'
down_revision: Union[str, Sequence[str], None] = '13914474515e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parallel_usage_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('url_extracted', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('endpoint_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('content_size_bytes', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parallel_usage_logs_created_at'), 'parallel_usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_parallel_usage_logs_endpoint_name'), 'parallel_usage_logs', ['endpoint_name'], unique=False)
    op.create_index(op.f('ix_parallel_usage_logs_organization_id'), 'parallel_usage_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_parallel_usage_logs_success'), 'parallel_usage_logs', ['success'], unique=False)
    op.create_index(op.f('ix_parallel_usage_logs_user_id'), 'parallel_usage_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parallel_usage_logs_user_id'), table_name='parallel_usage_logs')
    op.drop_index(op.f('ix_parallel_usage_logs_success'), table_name='parallel_usage_logs')
    op.drop_index(op.f('ix_parallel_usage_logs_organization_id'), table_name='parallel_usage_logs')
    op.drop_index(op.f('ix_parallel_usage_logs_endpoint_name'), table_name='parallel_usage_logs')
    op.drop_index(op.f('ix_parallel_usage_logs_created_at'), table_name='parallel_usage_logs')
    op.drop_table('parallel_usage_logs')
    # ### end Alembic commands ###
