"""add_auto_create_tickets_to_source

Revision ID: 24ab90129d1a
Revises: 20dfc5b10985
Create Date: 2025-12-17 12:37:57.128958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24ab90129d1a'
down_revision: Union[str, Sequence[str], None] = '20dfc5b10985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('auto_create_tickets', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'auto_create_tickets')
    # ### end Alembic commands ###
