"""add source table crud

Revision ID: 3e7e5f7ae4aa
Revises: 568cc1b65e22
Create Date: 2025-11-22 00:06:52.897519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3e7e5f7ae4aa"
down_revision: Union[str, Sequence[str], None] = "568cc1b65e22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("jurisdiction_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("WEB", "PDF", "API", name="sourcetype"),
            nullable=False,
        ),
        sa.Column(
            "scrape_frequency", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("next_scrape_time", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "auth_details_encrypted", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("scraping_rules", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sources_id"), "sources", ["id"], unique=False)
    op.create_index(
        op.f("ix_sources_is_deleted"), "sources", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_sources_jurisdiction_id"), "sources", ["jurisdiction_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sources_jurisdiction_id"), table_name="sources")
    op.drop_index(op.f("ix_sources_is_deleted"), table_name="sources")
    op.drop_index(op.f("ix_sources_id"), table_name="sources")
    op.drop_table("sources")
    # ### end Alembic commands ###
