"""add campaigns module and jurisdiction campaign fields

Revision ID: 52441cbb7dfa
Revises: 654a54ebe9da
Create Date: 2026-03-04 00:01:39.363006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '52441cbb7dfa'
down_revision: Union[str, Sequence[str], None] = '654a54ebe9da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('domain_description', sa.Text(), nullable=True),
    sa.Column('target_depth', sa.Enum('COUNTRY', 'STATE', 'CITY', name='campaigntargetdepth'), nullable=False),
    sa.Column('monitor_backend', sa.Enum('CELERY_BEAT', name='campaignmonitorbackend'), nullable=False),
    sa.Column('monitor_cadence', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('sources_per_jurisdiction', sa.Integer(), nullable=False),
    sa.Column('max_jurisdictions', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'TAXONOMY_READY', 'HYDRATING', 'DISCOVERING_SOURCES', 'SCRAPING', 'PUBLISHING', 'MONITORING', 'ACTIVE', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='campaignstatus'), nullable=False),
    sa.Column('taxonomy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('taxonomy_approved_by', sa.Uuid(), nullable=True),
    sa.Column('taxonomy_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('launched_by', sa.Uuid(), nullable=True),
    sa.Column('generation_model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('generation_config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['launched_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['taxonomy_approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index('ix_campaigns_organization_id', 'campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaigns_project_id'), 'campaigns', ['project_id'], unique=False)
    op.create_index('ix_campaigns_status', 'campaigns', ['status'], unique=False)
    op.create_table('campaign_execution_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('completed_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_execution_logs_campaign_id'), 'campaign_execution_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_execution_logs_id'), 'campaign_execution_logs', ['id'], unique=False)
    op.add_column('jurisdictions', sa.Column('campaign_id', sa.Uuid(), nullable=True))
    op.add_column('jurisdictions', sa.Column('auto_accept_changes', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_jurisdictions_campaign_id'), 'jurisdictions', ['campaign_id'], unique=False)
    op.create_foreign_key('jurisdictions_campaign_id_fkey', 'jurisdictions', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jurisdictions_campaign_id_fkey', 'jurisdictions', type_='foreignkey')
    op.drop_index(op.f('ix_jurisdictions_campaign_id'), table_name='jurisdictions')
    op.drop_column('jurisdictions', 'auto_accept_changes')
    op.drop_column('jurisdictions', 'campaign_id')
    op.drop_index(op.f('ix_campaign_execution_logs_id'), table_name='campaign_execution_logs')
    op.drop_index(op.f('ix_campaign_execution_logs_campaign_id'), table_name='campaign_execution_logs')
    op.drop_table('campaign_execution_logs')
    op.drop_index('ix_campaigns_status', table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_project_id'), table_name='campaigns')
    op.drop_index('ix_campaigns_organization_id', table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
