"""add_jurisdiction_scrape_job_id_to_scrape_job

Revision ID: 5260ea691bff
Revises: 15738e9d81d0
Create Date: 2026-01-09 19:29:33.036951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5260ea691bff'
down_revision: Union[str, Sequence[str], None] = '15738e9d81d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_jobs', sa.Column('jurisdiction_scrape_job_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_scrape_jobs_jurisdiction_scrape_job_id'), 'scrape_jobs', ['jurisdiction_scrape_job_id'], unique=False)
    op.create_foreign_key(None, 'scrape_jobs', 'jurisdiction_scrape_jobs', ['jurisdiction_scrape_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scrape_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_scrape_jobs_jurisdiction_scrape_job_id'), table_name='scrape_jobs')
    op.drop_column('scrape_jobs', 'jurisdiction_scrape_job_id')
    # ### end Alembic commands ###
