"""add_soft_delete_to_projects

Revision ID: 568cc1b65e22
Revises: c1bc173efb4e
Create Date: 2025-11-21 20:16:25.960079

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "568cc1b65e22"
down_revision: Union[str, Sequence[str], None] = "c1bc173efb4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("jurisdictions_project_id_fkey"), "jurisdictions", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("jurisdictions_parent_id_fkey"), "jurisdictions", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "jurisdictions", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "jurisdictions",
        "jurisdictions",
        ["parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("project_users_project_id_fkey"), "project_users", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "project_users", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("projects", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.add_column(
        "projects", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.execute("UPDATE projects SET is_deleted = false")
    op.alter_column("projects", "is_deleted", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "deleted_at")
    op.drop_column("projects", "is_deleted")
    op.drop_constraint(None, "project_users", type_="foreignkey")
    op.create_foreign_key(
        op.f("project_users_project_id_fkey"),
        "project_users",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.drop_constraint(None, "jurisdictions", type_="foreignkey")
    op.drop_constraint(None, "jurisdictions", type_="foreignkey")
    op.create_foreign_key(
        op.f("jurisdictions_parent_id_fkey"),
        "jurisdictions",
        "jurisdictions",
        ["parent_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("jurisdictions_project_id_fkey"),
        "jurisdictions",
        "projects",
        ["project_id"],
        ["id"],
    )
    # ### end Alembic commands ###
