"""Parent/child relationship, name duplication constraint

Revision ID: 639ff4afb64a
Revises: 92b6d9686574
Create Date: 2025-11-26 15:20:54.669082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '639ff4afb64a'
down_revision: Union[str, Sequence[str], None] = '5ee1506b7eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_revisions', 'ai_markdown_summary',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_unique_constraint('uix_project_name', 'jurisdictions', ['project_id', 'parent_id', 'name'])
    op.drop_constraint(op.f('jurisdictions_parent_id_fkey'), 'jurisdictions', type_='foreignkey')
    op.create_foreign_key(None, 'jurisdictions', 'jurisdictions', ['parent_id'], ['id'], ondelete='SET NULL')
    op.alter_column('sources', 'next_scrape_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.create_foreign_key(None, 'sources', 'jurisdictions', ['jurisdiction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.alter_column('sources', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sources', 'next_scrape_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'jurisdictions', type_='foreignkey')
    op.create_foreign_key(op.f('jurisdictions_parent_id_fkey'), 'jurisdictions', 'jurisdictions', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uix_project_name', 'jurisdictions', type_='unique')
    op.alter_column('data_revisions', 'ai_markdown_summary',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
