"""add membership and org active indexes

Revision ID: 642bebb50756
Revises: 6ab044401c2c
Create Date: 2025-12-03 14:54:07.762621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '642bebb50756'
down_revision: Union[str, Sequence[str], None] = '6ab044401c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_ba_default_payment_method_id', 'billing_accounts', 'billing_payment_methods', ['default_payment_method_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_index('ix_org_active_not_deleted', 'organizations', ['is_active'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_user_org_active_memberships', 'user_organizations', ['user_id', 'is_active'], unique=False, postgresql_where=sa.text('is_deleted IS false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_org_active_memberships', table_name='user_organizations', postgresql_where=sa.text('is_deleted IS false'))
    op.drop_index('ix_org_active_not_deleted', table_name='organizations', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint('fk_ba_default_payment_method_id', 'billing_accounts', type_='foreignkey')
    # ### end Alembic commands ###
