"""add project_bulk_blog_jobs table

Revision ID: 654a54ebe9da
Revises: cddd983138bb
Create Date: 2026-02-25 16:47:19.371511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '654a54ebe9da'
down_revision: Union[str, Sequence[str], None] = 'cddd983138bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_bulk_blog_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', name='projectbulkblogjobstatus'), nullable=False),
    sa.Column('totals', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('publish_requested', sa.Boolean(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_bulk_blog_jobs_id'), 'project_bulk_blog_jobs', ['id'], unique=False)
    op.create_index('ix_project_bulk_blog_jobs_project_active', 'project_bulk_blog_jobs', ['project_id'], unique=True, postgresql_where="status IN ('PENDING', 'IN_PROGRESS')")
    op.create_index(op.f('ix_project_bulk_blog_jobs_project_id'), 'project_bulk_blog_jobs', ['project_id'], unique=False)
    op.add_column('blog_generation_jobs', sa.Column('bulk_job_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_blog_generation_jobs_bulk_job_id'), 'blog_generation_jobs', ['bulk_job_id'], unique=False)
    op.create_foreign_key(None, 'blog_generation_jobs', 'project_bulk_blog_jobs', ['bulk_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_generation_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_blog_generation_jobs_bulk_job_id'), table_name='blog_generation_jobs')
    op.drop_column('blog_generation_jobs', 'bulk_job_id')
    op.drop_index(op.f('ix_project_bulk_blog_jobs_project_id'), table_name='project_bulk_blog_jobs')
    op.drop_index('ix_project_bulk_blog_jobs_project_active', table_name='project_bulk_blog_jobs', postgresql_where="status IN ('PENDING', 'IN_PROGRESS')")
    op.drop_index(op.f('ix_project_bulk_blog_jobs_id'), table_name='project_bulk_blog_jobs')
    op.drop_table('project_bulk_blog_jobs')
    # ### end Alembic commands ###
