"""Add secure default settings

Revision ID: 6ab044401c2c
Revises: f94d1e19a88c
Create Date: 2025-12-02 19:04:40.375432

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine.reflection import Inspector
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "6ab044401c2c"
down_revision: Union[str, Sequence[str], None] = "f94d1e19a88c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    inspector = Inspector.from_engine(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    if "billing_plans" not in inspector.get_table_names():
        op.create_table(
            "billing_plans",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
            sa.Column(
                "tier",
                sa.Enum("ESSENTIAL", "PROFESSIONAL", "ENTERPRISE", name="billingplantier"),
                nullable=False,
            ),
            sa.Column(
                "label", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
            ),
            sa.Column(
                "description", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
            ),
            sa.Column(
                "interval",
                sa.Enum("MONTH", "YEAR", name="billingplaninterval"),
                nullable=False,
            ),
            sa.Column(
                "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
            ),
            sa.Column("amount", sa.Integer(), nullable=False),
            sa.Column(
                "stripe_product_id",
                sqlmodel.sql.sqltypes.AutoString(length=255),
                nullable=False,
            ),
            sa.Column(
                "stripe_price_id",
                sqlmodel.sql.sqltypes.AutoString(length=255),
                nullable=False,
            ),
            sa.Column("features", sa.JSON(), server_default="[]", nullable=False),
            sa.Column(
                "is_most_popular", sa.Boolean(), server_default="false", nullable=False
            ),
            sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
            sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint(
                "code",
                "interval",
                "currency",
                name="uq_billing_plan_code_interval_currency",
            ),
        )
        op.create_index(
            op.f("ix_billing_plans_code"), "billing_plans", ["code"], unique=False
        )
        op.create_index(op.f("ix_billing_plans_id"), "billing_plans", ["id"], unique=False)
    if "otps" not in inspector.get_table_names():
        op.create_table(
            "otps",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("user_id", sa.Uuid(), nullable=False),
            sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
            sa.Column("expires_at", sa.DateTime(), nullable=False),
            sa.Column("is_used", sa.Boolean(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["users.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_otps_code"), "otps", ["code"], unique=False)
        op.create_index(op.f("ix_otps_id"), "otps", ["id"], unique=False)
        op.create_index(op.f("ix_otps_user_id"), "otps", ["user_id"], unique=False)
    if "revision_notifications" not in inspector.get_table_names():
        op.create_table(
            "revision_notifications",
            sa.Column("notification_id", sa.Uuid(), nullable=False),
            sa.Column("revision_id", sa.Uuid(), nullable=False),
            sa.Column("user_id", sa.Uuid(), nullable=False),
            sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column(
                "status",
                sa.Enum("PENDING", "SENT", "FAILED", name="notificationstatus"),
                nullable=False,
            ),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("sent_at", sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(
                ["revision_id"],
                ["data_revisions.id"],
            ),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["users.id"],
            ),
            sa.PrimaryKeyConstraint("notification_id"),
        )
        op.drop_index(
            op.f("ix_billing_subscriptions_billing_account_id"),
            table_name="billing_subscriptions",
        )
        op.drop_index(
            op.f("ix_billing_subscriptions_id"), table_name="billing_subscriptions"
        )
        op.drop_index(
            op.f("ix_billing_subscriptions_stripe_subscription_id"),
            table_name="billing_subscriptions",
        )
        op.drop_table("billing_subscriptions")
        op.drop_table("testuser")
        op.drop_index(
            op.f("ix_billing_invoices_stripe_invoice_id"), table_name="billing_invoices"
        )
        op.create_index(
            op.f("ix_billing_invoices_stripe_invoice_id"),
            "billing_invoices",
            ["stripe_invoice_id"],
            unique=True,
        )
        op.add_column(
            "invitations",
            sa.Column(
                "organization_name",
                sqlmodel.sql.sqltypes.AutoString(length=255),
                nullable=True,
            ),
        )
        op.create_index(
            op.f("ix_invitations_organization_name"),
            "invitations",
            ["organization_name"],
            unique=False,
        )
        op.add_column(
            "organizations",
            sa.Column(
                "location", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
            ),
        )
        op.add_column(
            "organizations",
            sa.Column("plan", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        )
        op.alter_column(
            "organizations",
            "settings",
            existing_type=sa.JSON(),
            server_default=sa.text(
                '\'{"visibility": "private", "require_strong_passwords": true, '
                '"require_2fa": true, "allow_external_sharing": false, '
                '"audit_logging_enabled": true, "project_default_privacy": "private"}\'::json'
            ),
            existing_nullable=False,
        )
        op.add_column(
            "organizations",
            sa.Column(
                "logo_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
            ),
        )
        op.add_column(
            "organizations",
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        )
        op.create_index(
            "ux_organizations_active_name",
            "organizations",
            [sa.literal_column("lower(name)")],
            unique=True,
            postgresql_where=sa.text("deleted_at IS NULL"),
        )
        op.add_column(
            "user_organizations",
            sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        )
        op.add_column(
            "user_organizations",
            sa.Column(
                "department", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
            ),
        )
        op.add_column(
            "user_organizations", sa.Column("is_deleted", sa.Boolean(), nullable=False)
        )
        op.add_column(
            "user_organizations",
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        )
        op.add_column(
            "users",
            sa.Column(
                "provider_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            ),
        )
        op.add_column(
            "users",
            sa.Column(
                "profile_picture_url",
                sqlmodel.sql.sqltypes.AutoString(length=500),
                nullable=True,
            ),
        )
        op.add_column("users", sa.Column("provider_profile_data", sa.JSON(), nullable=True))
        op.add_column(
            "users",
            sa.Column(
                "avatar_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
            ),
        )
        op.alter_column(
            "users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        op.create_index(
            op.f("ix_users_provider_user_id"), "users", ["provider_user_id"], unique=False
        )
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    inspector = Inspector.from_engine(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_provider_user_id"), table_name="users")
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("users", "avatar_url")
    op.drop_column("users", "provider_profile_data")
    op.drop_column("users", "profile_picture_url")
    op.drop_column("users", "provider_user_id")
    op.drop_column("user_organizations", "deleted_at")
    op.drop_column("user_organizations", "is_deleted")
    op.drop_column("user_organizations", "department")
    op.drop_column("user_organizations", "title")
    op.drop_index(
        "ux_organizations_active_name",
        table_name="organizations",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_column("organizations", "deleted_at")
    op.drop_column("organizations", "logo_url")
    op.drop_column("organizations", "plan")
    op.drop_column("organizations", "location")
    op.drop_index(op.f("ix_invitations_organization_name"), table_name="invitations")
    op.drop_column("invitations", "organization_name")
    op.drop_index(
        op.f("ix_billing_invoices_stripe_invoice_id"), table_name="billing_invoices"
    )
    op.create_index(
        op.f("ix_billing_invoices_stripe_invoice_id"),
        "billing_invoices",
        ["stripe_invoice_id"],
        unique=False,
    )
    if "testuser" not in inspector.get_table_names():
        op.create_table(
            "testuser",
            sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
            sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
            sa.PrimaryKeyConstraint("id", name=op.f("testuser_pkey")),
        )
    if "billing_subscriptions" not in inspector.get_table_names():
        op.create_table(
            "billing_subscriptions",
            sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
            sa.Column("billing_account_id", sa.UUID(), autoincrement=False, nullable=False),
            sa.Column(
                "stripe_subscription_id",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=False,
            ),
            sa.Column(
                "stripe_price_id",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=True,
            ),
            sa.Column(
                "plan",
                postgresql.ENUM("MONTHLY", "YEARLY", name="subscriptionplan"),
                autoincrement=False,
                nullable=False,
            ),
            sa.Column(
                "status",
                postgresql.ENUM(
                    "INCOMPLETE",
                    "INCOMPLETE_EXPIRED",
                    "TRIALING",
                    "ACTIVE",
                    "PAST_DUE",
                    "CANCELED",
                    "UNPAID",
                    "PAUSED",
                    name="subscriptionstatus",
                ),
                autoincrement=False,
                nullable=False,
            ),
            sa.Column(
                "current_period_start",
                postgresql.TIMESTAMP(timezone=True),
                autoincrement=False,
                nullable=False,
            ),
            sa.Column(
                "current_period_end",
                postgresql.TIMESTAMP(timezone=True),
                autoincrement=False,
                nullable=False,
            ),
            sa.Column(
                "cancel_at_period_end", sa.BOOLEAN(), autoincrement=False, nullable=False
            ),
            sa.Column(
                "canceled_at",
                postgresql.TIMESTAMP(timezone=True),
                autoincrement=False,
                nullable=True,
            ),
            sa.Column(
                "ended_at",
                postgresql.TIMESTAMP(timezone=True),
                autoincrement=False,
                nullable=True,
            ),
            sa.Column(
                "trial_start",
                postgresql.TIMESTAMP(timezone=True),
                autoincrement=False,
                nullable=True,
            ),
            sa.Column(
                "trial_end",
                postgresql.TIMESTAMP(timezone=True),
                autoincrement=False,
                nullable=True,
            ),
            sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
            sa.Column(
                "metadata",
                postgresql.JSON(astext_type=sa.Text()),
                server_default=sa.text("'{}'::json"),
                autoincrement=False,
                nullable=False,
            ),
            sa.Column(
                "created_at",
                postgresql.TIMESTAMP(timezone=True),
                autoincrement=False,
                nullable=False,
            ),
            sa.Column(
                "updated_at",
                postgresql.TIMESTAMP(timezone=True),
                autoincrement=False,
                nullable=False,
            ),
            sa.ForeignKeyConstraint(
                ["billing_account_id"],
                ["billing_accounts.id"],
                name=op.f("billing_subscriptions_billing_account_id_fkey"),
                ondelete="CASCADE",
            ),
            sa.PrimaryKeyConstraint("id", name=op.f("billing_subscriptions_pkey")),
        )
        op.create_index(
            op.f("ix_billing_subscriptions_stripe_subscription_id"),
            "billing_subscriptions",
            ["stripe_subscription_id"],
            unique=True,
        )
        op.create_index(
            op.f("ix_billing_subscriptions_id"),
            "billing_subscriptions",
            ["id"],
            unique=False,
        )
        op.create_index(
            op.f("ix_billing_subscriptions_billing_account_id"),
            "billing_subscriptions",
            ["billing_account_id"],
            unique=False,
        )
        op.drop_table("revision_notifications")
        op.drop_index(op.f("ix_otps_user_id"), table_name="otps")
        op.drop_index(op.f("ix_otps_id"), table_name="otps")
        op.drop_index(op.f("ix_otps_code"), table_name="otps")
        op.drop_table("otps")
        op.drop_index(op.f("ix_billing_plans_id"), table_name="billing_plans")
        op.drop_index(op.f("ix_billing_plans_code"), table_name="billing_plans")
        op.drop_table("billing_plans")
        # ### end Alembic commands ###
