"""add source verification tracking fields

Revision ID: 6b629fc3f748
Revises: e1c4b9e6d2a1
Create Date: 2026-04-05 00:37:31.961889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6b629fc3f748'
down_revision: Union[str, Sequence[str], None] = 'e1c4b9e6d2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'sources',
        sa.Column(
            'verification_status',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.add_column(
        'sources',
        sa.Column(
            'verification_attempts',
            sa.Integer(),
            nullable=False,
            server_default='0',
        ),
    )
    op.add_column(
        'sources',
        sa.Column(
            'last_verification_at',
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'last_verification_at')
    op.drop_column('sources', 'verification_attempts')
    op.drop_column('sources', 'verification_status')
    # ### end Alembic commands ###
