"""add_jurisdiction_changes_table

Revision ID: 6f6ede66d8df
Revises: 0b0e88f773cf
Create Date: 2026-01-16 23:24:16.315105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6f6ede66d8df'
down_revision: Union[str, Sequence[str], None] = '0b0e88f773cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisdiction_changes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('jurisdiction_scrape_job_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('change_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change_index', sa.Integer(), nullable=False),
    sa.Column('ticket_created', sa.Boolean(), nullable=False),
    sa.Column('change_accepted', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['jurisdiction_scrape_job_id'], ['jurisdiction_scrape_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jurisdiction_changes_accepted_by_user_id'), 'jurisdiction_changes', ['accepted_by_user_id'], unique=False)
    op.create_index(op.f('ix_jurisdiction_changes_change_accepted'), 'jurisdiction_changes', ['change_accepted'], unique=False)
    op.create_index(op.f('ix_jurisdiction_changes_field_name'), 'jurisdiction_changes', ['field_name'], unique=False)
    op.create_index(op.f('ix_jurisdiction_changes_id'), 'jurisdiction_changes', ['id'], unique=False)
    op.create_index(op.f('ix_jurisdiction_changes_jurisdiction_scrape_job_id'), 'jurisdiction_changes', ['jurisdiction_scrape_job_id'], unique=False)
    op.create_index(op.f('ix_jurisdiction_changes_ticket_created'), 'jurisdiction_changes', ['ticket_created'], unique=False)
    op.add_column('tickets', sa.Column('jurisdiction_change_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_tickets_jurisdiction_change_id'), 'tickets', ['jurisdiction_change_id'], unique=False)
    op.create_foreign_key(None, 'tickets', 'jurisdiction_changes', ['jurisdiction_change_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_jurisdiction_change_id'), table_name='tickets')
    op.drop_column('tickets', 'jurisdiction_change_id')
    op.drop_index(op.f('ix_jurisdiction_changes_ticket_created'), table_name='jurisdiction_changes')
    op.drop_index(op.f('ix_jurisdiction_changes_jurisdiction_scrape_job_id'), table_name='jurisdiction_changes')
    op.drop_index(op.f('ix_jurisdiction_changes_id'), table_name='jurisdiction_changes')
    op.drop_index(op.f('ix_jurisdiction_changes_field_name'), table_name='jurisdiction_changes')
    op.drop_index(op.f('ix_jurisdiction_changes_change_accepted'), table_name='jurisdiction_changes')
    op.drop_index(op.f('ix_jurisdiction_changes_accepted_by_user_id'), table_name='jurisdiction_changes')
    op.drop_table('jurisdiction_changes')
    # ### end Alembic commands ###
