"""Make jurisdiction description and source name optional

Revision ID: 79a4e5e7506c
Revises: 657231732a9b
Create Date: 2025-12-08 10:40:58.666600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '79a4e5e7506c'
down_revision: Union[str, Sequence[str], None] = '657231732a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jurisdictions', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sources', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jurisdictions', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
