"""initial waitlist table

Revision ID: 7ef99f328402
Revises:
Create Date: 2025-11-17 10:23:05.957483

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ef99f328402"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "waitlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_email", sa.String(length=255), nullable=False),
        sa.Column("organization_name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_waitlist_organization_email"),
        "waitlist",
        ["organization_email"],
        unique=True,
    )
    op.create_index(
        op.f("ix_waitlist_organization_name"),
        "waitlist",
        ["organization_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_waitlist_organization_name"), table_name="waitlist")
    op.drop_index(op.f("ix_waitlist_organization_email"), table_name="waitlist")
    op.drop_table("waitlist")
    # ### end Alembic commands ###
