"""add_comments_and_content_jsonb

Revision ID: 830aff3eb0e9
Revises: 1af7ec7b0800
Create Date: 2026-01-23 16:00:30.020490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830aff3eb0e9'
down_revision: Union[str, Sequence[str], None] = '1af7ec7b0800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('attachments', sa.JSON(), nullable=True))
    op.alter_column('comments', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('comments', 'attachments')
    # ### end Alembic commands ###
