"""update source and data revision table

Revision ID: 8db953970cc0
Revises: b398f6b7c7db
Create Date: 2025-11-26 01:31:04.312702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8db953970cc0'
down_revision: Union[str, Sequence[str], None] = 'b398f6b7c7db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_revisions', sa.Column('content_hash', sa.String(), nullable=True))
    op.create_index('ix_data_revisions_content_hash', 'data_revisions', ['content_hash'], unique=False)
    op.add_column('data_revisions', sa.Column('ai_markdown_summary', sa.Text(), nullable=True))
    op.add_column('data_revisions', sa.Column('ai_confidence_score', sa.Float(), nullable=True))
    op.alter_column('jurisdictions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('jurisdictions', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jurisdictions', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('jurisdictions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('data_revisions', 'ai_confidence_score')
    op.drop_column('data_revisions', 'ai_markdown_summary')
    op.drop_index('ix_data_revisions_content_hash', table_name='data_revisions')
    op.drop_column('data_revisions', 'content_hash')
    # ### end Alembic commands ###
