"""add_scrape_jobs_table

Revision ID: 8f7358211e24
Revises: 642bebb50756
Create Date: 2025-12-04 10:48:31.702015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8f7358211e24'
down_revision: Union[str, Sequence[str], None] = '642bebb50756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='scrapejobstatus'), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_revision_id', sa.Uuid(), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_revision_id'], ['data_revisions.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_jobs_data_revision_id'), 'scrape_jobs', ['data_revision_id'], unique=False)
    op.create_index(op.f('ix_scrape_jobs_id'), 'scrape_jobs', ['id'], unique=False)
    op.create_index('ix_scrape_jobs_source_active', 'scrape_jobs', ['source_id'], unique=True, postgresql_where="status IN ('PENDING', 'IN_PROGRESS')")
    op.create_index(op.f('ix_scrape_jobs_source_id'), 'scrape_jobs', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrape_jobs_source_id'), table_name='scrape_jobs')
    op.drop_index('ix_scrape_jobs_source_active', table_name='scrape_jobs', postgresql_where="status IN ('PENDING', 'IN_PROGRESS')")
    op.drop_index(op.f('ix_scrape_jobs_id'), table_name='scrape_jobs')
    op.drop_index(op.f('ix_scrape_jobs_data_revision_id'), table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    # ### end Alembic commands ###
