"""update_role_model_with_tempname_hierarchy

Revision ID: 9adb4fbea198
Revises: d227f5996841
Create Date: 2025-12-04 21:12:49.414101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9adb4fbea198'
down_revision: Union[str, Sequence[str], None] = 'd227f5996841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('hierarchy_level', sa.Integer(), nullable=False))
    op.add_column('roles', sa.Column('template_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('roles', 'template_name')
    op.drop_column('roles', 'hierarchy_level')
    # ### end Alembic commands ###
