"""role_templates_model_for_permissions_json

Revision ID: a249039be841
Revises: 9adb4fbea198
Create Date: 2025-12-04 21:16:21.951569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a249039be841'
down_revision: Union[str, Sequence[str], None] = '9adb4fbea198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_templates_id'), 'role_templates', ['id'], unique=False)
    op.create_index(op.f('ix_role_templates_name'), 'role_templates', ['name'], unique=True)
    # ### end Alembic commands ###

    op.execute("""
        INSERT INTO role_templates (id, name, display_name, description, permissions, is_system, hierarchy_level, created_at, updated_at)
        VALUES 
        (gen_random_uuid(), 'owner', 'Owner', 'Organization owner with full permissions including deletion', 
         '{"manage_users": true, "invite_users": true, "deactivate_users": true, "assign_roles": true, 
           "create_roles": true, "edit_roles": true, "delete_roles": true, "view_roles": true,
           "manage_organization": true, "configure_sso": true, "manage_billing": true, "delete_organization": true,
           "create_projects": true, "edit_projects": true, "delete_projects": true, "view_projects": true,
           "create_jurisdictions": true, "edit_jurisdictions": true, "delete_jurisdictions": true, "view_jurisdictions": true,
           "create_sources": true, "edit_sources": true, "delete_sources": true, "view_sources": true, "trigger_scraping": true,
           "create_tickets": true, "edit_tickets": true, "delete_tickets": true, "view_tickets": true, 
           "assign_tickets": true, "close_tickets": true,
           "invite_participants": true, "revoke_participant_access": true,
           "view_revisions": true, "export_data": true, "manage_api_keys": true}'::jsonb,
         true, 4, NOW(), NOW()),
        
        (gen_random_uuid(), 'admin', 'Admin', 'Administrator with full permissions except organization deletion',
         '{"manage_users": true, "invite_users": true, "deactivate_users": true, "assign_roles": true,
           "create_roles": true, "edit_roles": true, "delete_roles": true, "view_roles": true,
           "manage_organization": true, "configure_sso": true, "manage_billing": true,
           "create_projects": true, "edit_projects": true, "delete_projects": true, "view_projects": true,
           "create_jurisdictions": true, "edit_jurisdictions": true, "delete_jurisdictions": true, "view_jurisdictions": true,
           "create_sources": true, "edit_sources": true, "delete_sources": true, "view_sources": true, "trigger_scraping": true,
           "create_tickets": true, "edit_tickets": true, "delete_tickets": true, "view_tickets": true,
           "assign_tickets": true, "close_tickets": true,
           "invite_participants": true, "revoke_participant_access": true,
           "view_revisions": true, "export_data": true, "manage_api_keys": true}'::jsonb,
         true, 3, NOW(), NOW()),
        
        (gen_random_uuid(), 'manager', 'Manager', 'Team manager with elevated project management permissions',
         '{"invite_users": true, "view_roles": true,
           "create_projects": true, "edit_projects": true, "view_projects": true,
           "create_jurisdictions": true, "edit_jurisdictions": true, "view_jurisdictions": true,
           "create_sources": true, "edit_sources": true, "view_sources": true, "trigger_scraping": true,
           "create_tickets": true, "edit_tickets": true, "view_tickets": true, "assign_tickets": true, "close_tickets": true,
           "invite_participants": true, "view_revisions": true, "export_data": true}'::jsonb,
         true, 2, NOW(), NOW()),
        
        (gen_random_uuid(), 'member', 'Member', 'Organization member with basic permissions',
         '{"view_projects": true, "view_jurisdictions": true, "view_sources": true,
           "view_tickets": true, "create_tickets": true, "edit_tickets": true, "view_revisions": true}'::jsonb,
         true, 1, NOW(), NOW())
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_templates_name'), table_name='role_templates')
    op.drop_index(op.f('ix_role_templates_id'), table_name='role_templates')
    op.drop_table('role_templates')
    # ### end Alembic commands ###
