"""add_is_approved_and_approved_at_to_users

Revision ID: ab732ba075d6
Revises: 830aff3eb0e9
Create Date: 2026-01-26 22:36:20.055617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab732ba075d6'
down_revision: Union[str, Sequence[str], None] = '830aff3eb0e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add is_approved column with server default for existing rows
    op.add_column(
        'users',
        sa.Column('is_approved', sa.Boolean(), nullable=False, server_default='true')
    )
    # Remove server default (new rows will use model default)
    op.alter_column('users', 'is_approved', server_default=None)
    
    # Add approved_at column (nullable)
    op.add_column('users', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    
    # Create index
    op.create_index(op.f('ix_users_is_approved'), 'users', ['is_approved'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_approved'), table_name='users')
    op.drop_column('users', 'approved_at')
    op.drop_column('users', 'is_approved')
    # ### end Alembic commands ###
