"""add jurisdiction to notification

Revision ID: c18bded7b6a0
Revises: bf283f4bc632
Create Date: 2025-12-04 22:25:50.728435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c18bded7b6a0'
down_revision: Union[str, Sequence[str], None] = 'bf283f4bc632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revision_notifications', sa.Column('jurisdiction_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_revision_notifications_jurisdiction_id'), 'revision_notifications', ['jurisdiction_id'], unique=False)
    op.create_foreign_key(None, 'revision_notifications', 'jurisdictions', ['jurisdiction_id'], ['id'])
    op.alter_column('scrape_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scrape_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(None, 'revision_notifications', type_='foreignkey')
    op.drop_index(op.f('ix_revision_notifications_jurisdiction_id'), table_name='revision_notifications')
    op.drop_column('revision_notifications', 'jurisdiction_id')
    # ### end Alembic commands ###
