"""Word Token model for quick search look up

Revision ID: cddd983138bb
Revises: 5488cdfb1498
Create Date: 2026-02-19 15:41:08.465158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cddd983138bb'
down_revision: Union[str, Sequence[str], None] = '5488cdfb1498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('word_token', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['jurisdiction_blog_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_post_tokens_id'), 'blog_post_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_blog_post_tokens_post_id'), 'blog_post_tokens', ['post_id'], unique=False)
    op.create_index(op.f('ix_blog_post_tokens_word_token'), 'blog_post_tokens', ['word_token'], unique=False)
    op.alter_column('jurisdiction_blog_posts', 'keywords',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_constraint(op.f('uq_blog_post_slug'), 'jurisdiction_blog_posts', type_='unique')
    op.drop_index(op.f('ix_jurisdiction_blog_posts_slug'), table_name='jurisdiction_blog_posts')
    op.create_index(op.f('ix_jurisdiction_blog_posts_slug'), 'jurisdiction_blog_posts', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jurisdiction_blog_posts_slug'), table_name='jurisdiction_blog_posts')
    op.create_index(op.f('ix_jurisdiction_blog_posts_slug'), 'jurisdiction_blog_posts', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_blog_post_slug'), 'jurisdiction_blog_posts', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('jurisdiction_blog_posts', 'keywords',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_index(op.f('ix_blog_post_tokens_word_token'), table_name='blog_post_tokens')
    op.drop_index(op.f('ix_blog_post_tokens_post_id'), table_name='blog_post_tokens')
    op.drop_index(op.f('ix_blog_post_tokens_id'), table_name='blog_post_tokens')
    op.drop_table('blog_post_tokens')
    # ### end Alembic commands ###
