"""remove global organization constraint

Revision ID: d2cfa17a3670
Revises: d79d3ded8eef
Create Date: 2025-12-14 05:55:12.389907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2cfa17a3670'
down_revision: Union[str, Sequence[str], None] = 'd79d3ded8eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Unrelated changes to comments table removed manually to fix upgrade error

    op.drop_index(op.f('ux_organizations_active_name'), table_name='organizations', postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ux_organizations_active_name'), 'organizations', [sa.literal_column('lower(name::text)')], unique=True, postgresql_where='(deleted_at IS NULL)')
    # Unrelated changes to comments table removed manually

    # ### end Alembic commands ###
