"""add organization_name to invitations table and is_deleted to orgnization table

Revision ID: d5328ba9783c
Revises: e40a68f35eaa
Create Date: 2025-11-28 15:21:44.494270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd5328ba9783c'
down_revision: Union[str, Sequence[str], None] = 'e40a68f35eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('organization_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_invitations_organization_name'), 'invitations', ['organization_name'], unique=False)
    op.add_column('organizations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'deleted_at')
    op.drop_index(op.f('ix_invitations_organization_name'), table_name='invitations')
    op.drop_column('invitations', 'organization_name')
    # ### end Alembic commands ###
