"""add is_baseliine to revision

Revision ID: e051c40163e2
Revises: 8f7358211e24
Create Date: 2025-12-04 13:11:28.706317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e051c40163e2'
down_revision: Union[str, Sequence[str], None] = '8f7358211e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_revisions', sa.Column('is_baseline', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_revisions', 'is_baseline')
    # ### end Alembic commands ###
