"""create contact us table

Revision ID: e40a68f35eaa
Revises: 639ff4afb64a
Create Date: 2025-11-27 18:09:53.101508

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40a68f35eaa'
down_revision: Union[str, Sequence[str], None] = '639ff4afb64a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_us',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_us_email'), 'contact_us', ['email'], unique=False)
    op.create_index(op.f('ix_contact_us_id'), 'contact_us', ['id'], unique=False)
    op.add_column('sources', sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sources', sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'last_error')
    op.drop_column('sources', 'last_scraped_at')
    op.drop_index(op.f('ix_contact_us_id'), table_name='contact_us')
    op.drop_index(op.f('ix_contact_us_email'), table_name='contact_us')
    op.drop_table('contact_us')
    # ### end Alembic commands ###
