"""Added: Billing plan model

Revision ID: eba4d89ad4c9
Revises: 924acaf3d7b8
Create Date: 2025-11-30 02:34:49.751313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import exc

# revision identifiers, used by Alembic.
revision: str = 'eba4d89ad4c9'
down_revision: Union[str, Sequence[str], None] = '924acaf3d7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # use IF EXISTS to avoid failure if index is absent
    op.execute("DROP INDEX IF EXISTS ix_billing_subscriptions_billing_account_id")
    op.execute("DROP INDEX IF EXISTS ix_billing_subscriptions_id")
    op.execute("DROP INDEX IF EXISTS ix_billing_subscriptions_stripe_subscription_id")
    op.execute("DROP TABLE IF EXISTS billing_subscriptions CASCADE")
    
    try:
        op.drop_constraint(op.f('fk_billing_accounts_default_payment_method'), 'billing_accounts', type_='foreignkey')
    except exc.ProgrammingError:
        pass
    
    op.execute("DROP INDEX IF EXISTS ix_billing_invoices_stripe_invoice_id")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_billing_invoices_stripe_invoice_id ON billing_invoices (stripe_invoice_id)")
    
    op.execute("""
        ALTER TABLE refresh_token_metadata
        ADD COLUMN IF NOT EXISTS issued_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
    """)
    
    try:
        op.alter_column('refresh_token_metadata', 'provider_token_exp',
                   existing_type=sa.BIGINT(),
                   type_=sa.Integer(),
                   existing_nullable=True)
    except exc.ProgrammingError:
        pass
    
    try:
        op.alter_column('refresh_token_metadata', 'expires_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=False)
    except exc.ProgrammingError:
        pass
    op.execute("DROP INDEX IF EXISTS ix_refresh_token_metadata_is_revoked")
    op.execute("DROP INDEX IF EXISTS ix_refresh_token_metadata_jti")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_refresh_token_metadata_jti ON refresh_token_metadata (jti)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_refresh_token_metadata_id ON refresh_token_metadata (id)")
    
    op.execute("""
        ALTER TABLE refresh_token_metadata
        DROP COLUMN IF EXISTS created_at
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token_metadata', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_refresh_token_metadata_id'), table_name='refresh_token_metadata')
    op.drop_index(op.f('ix_refresh_token_metadata_jti'), table_name='refresh_token_metadata')
    op.create_index(op.f('ix_refresh_token_metadata_jti'), 'refresh_token_metadata', ['jti'], unique=False)
    op.create_index(op.f('ix_refresh_token_metadata_is_revoked'), 'refresh_token_metadata', ['is_revoked'], unique=False)
    op.alter_column('refresh_token_metadata', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('refresh_token_metadata', 'provider_token_exp',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_column('refresh_token_metadata', 'issued_at')
    op.drop_index(op.f('ix_billing_invoices_stripe_invoice_id'), table_name='billing_invoices')
    op.create_index(op.f('ix_billing_invoices_stripe_invoice_id'), 'billing_invoices', ['stripe_invoice_id'], unique=False)
    op.create_foreign_key(op.f('fk_billing_accounts_default_payment_method'), 'billing_accounts', 'billing_payment_methods', ['default_payment_method_id'], ['id'], ondelete='SET NULL')
    op.create_table('billing_subscriptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('billing_account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('stripe_price_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('plan', postgresql.ENUM('MONTHLY', 'YEARLY', name='subscriptionplan'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('INCOMPLETE', 'INCOMPLETE_EXPIRED', 'TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'UNPAID', 'PAUSED', name='subscriptionstatus'), autoincrement=False, nullable=False),
    sa.Column('current_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('current_period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('cancel_at_period_end', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('canceled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('trial_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('trial_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['billing_account_id'], ['billing_accounts.id'], name=op.f('billing_subscriptions_billing_account_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('billing_subscriptions_pkey'))
    )
    op.create_index(op.f('ix_billing_subscriptions_stripe_subscription_id'), 'billing_subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_billing_subscriptions_id'), 'billing_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_billing_account_id'), 'billing_subscriptions', ['billing_account_id'], unique=False)
    # ### end Alembic commands ###
