"""Pydantic schemas for jurisdiction blog post operations.

Defines request and response models for blog generation and retrieval endpoints.
All schemas follow the project's standard response format patterns.
"""

from datetime import datetime
from typing import Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator


class RelatedJurisdictionResponse(BaseModel):
    """Response schema for a single related jurisdiction recommendation card."""

    type: str = Field(
        description=(
            "Relationship type (e.g. Subdivision, Neighboring Country, "
            "Reference Framework, Similar Framework)"
        )
    )
    name: str = Field(description="Jurisdiction name")
    region: str = Field(description="Country or region name")
    url: str = Field(description="URL link to the target blog post")


class BlogPostResponse(BaseModel):
    """Response schema for a jurisdiction blog post.

    Returns the full blog post with all metadata for display or editing.
    Includes content in Markdown format and SEO metadata.

    Attributes:
        id: Unique identifier for the blog post.
        jurisdiction_id: Foreign key to the jurisdiction.
        title: SEO-friendly blog post title.
        slug: URL-safe slug (e.g., "eor-guide-california").
        content: Full Markdown-formatted blog post body.
        meta_description: SEO meta description (120-160 chars).
        keywords: Array of SEO keywords.
        breadcrumbs: Precomputed breadcrumb trail for SEO markup.
        is_published: Whether the post is publicly visible.
        version: Content version number (increments on regeneration).
        content_hash: SHA-256 hash of source data at generation.
        generation_model: LLM model used for generation (None for placeholders).
        generated_at: Timestamp when content was last generated by LLM.
        created_at: Timestamp when first created.
        updated_at: Timestamp of last update.
        published_at: Timestamp when published (None if unpublished).

    Examples:
        >>> response = BlogPostResponse.model_validate(blog_post)
        >>> print(response.slug)
        eor-guide-california
    """

    id: UUID
    jurisdiction_id: UUID
    title: str
    slug: str
    content: str
    content_html: str
    meta_description: str
    keywords: List[str]
    breadcrumbs: List[Dict[str, str]] = Field(
        default_factory=list,
        description="Precomputed breadcrumb trail: [{'name': str, 'url': str}, ...]",
    )
    is_published: bool
    version: int
    content_hash: str
    generation_model: Optional[str]
    generated_at: Optional[datetime]
    created_at: datetime
    updated_at: datetime
    published_at: Optional[datetime]
    public_url: Optional[str] = None
    resource_path: Optional[str] = None
    related_jurisdictions: List[RelatedJurisdictionResponse] = Field(
        default_factory=list,
        description="Dynamic recommendations and regional cross-comparisons.",
    )

    model_config = ConfigDict(from_attributes=True)


class BlogGenerateResponse(BaseModel):
    """Response schema after triggering blog generation.

    Returns the generation status and basic metadata. Used for both
    inline (auto-trigger) and background (manual trigger) generation.

    Attributes:
        status: Generation result ("success", "skipped", "failed", "placeholder").
        jurisdiction_id: The jurisdiction for which the blog was generated.
        message: Human-readable status message.
        version: Version number of the generated post (None if failed).

    Examples:
        >>> response = BlogGenerateResponse(
        ...     status="success",
        ...     jurisdiction_id=jur_id,
        ...     message="Blog post generated successfully",
        ...     version=2
        ... )
    """

    status: str
    jurisdiction_id: UUID
    message: str
    version: Optional[int] = None


class BlogLLMOutput(BaseModel):
    """Pydantic model for validating structured LLM output.

    Used as response_model in LLM calls to enforce structured output
    and automatic validation via instructor/Pydantic integration.

    Attributes:
        title: SEO-friendly blog post title.
        meta_description: SEO meta description (120-160 characters).
        keywords: Array of 3-8 relevant SEO keywords.
        content: Full blog post body in Markdown format (min 100 chars).

    Examples:
        >>> # Used in LLM call:
        >>> response = await llm_manager.generate_with_tracking(
        ...     prompt=prompt,
        ...     response_model=BlogLLMOutput,
        ...     ...
        ... )
    """

    title: str = Field(min_length=10, max_length=200)
    meta_description: str = Field(min_length=50)
    keywords: List[str] = Field(min_length=3, max_length=8)
    content: str = Field(min_length=100)

    @field_validator("meta_description", mode="before")
    @classmethod
    def truncate_meta_description(cls, v: str) -> str:
        """Truncate meta_description to 160 characters if the LLM returns a longer string."""
        if isinstance(v, str) and len(v) > 160:
            return v[:157] + "..."
        return v


class BlogPublishRequest(BaseModel):
    """Request schema for publishing/unpublishing a blog post.

    Attributes:
        is_published: True to publish, False to unpublish.

    Examples:
        >>> payload = BlogPublishRequest(is_published=True)
    """

    is_published: bool


class PublicBlogPostResponse(BaseModel):
    """Response schema for a publicly visible blog post.

    Used by the public (unauthenticated) blog API consumed by the FE SSG
    build pipeline and search crawlers. Excludes internal fields like
    ``content_hash`` and ``generation_model``.

    Attributes:
        id: Unique identifier.
        jurisdiction_id: Parent jurisdiction.
        title: SEO-friendly title.
        slug: URL-safe slug.
        content_html: Pre-rendered HTML body fragment.
        meta_description: SEO meta description (120-160 chars).
        keywords: Array of SEO keywords.
        published_at: Timestamp when published.
        updated_at: Last-updated timestamp.

    Examples:
        >>> schema = PublicBlogPostResponse.model_validate(post)
        >>> print(schema.slug)
        eor-guide-california
    """

    id: UUID
    jurisdiction_id: UUID
    title: str
    slug: str
    content_html: str
    meta_description: str
    keywords: List[str]
    published_at: Optional[datetime]
    updated_at: datetime
    public_url: Optional[str] = None
    resource_path: Optional[str] = None
    related_jurisdictions: List[RelatedJurisdictionResponse] = Field(
        default_factory=list,
        description="Dynamic recommendations and regional cross-comparisons.",
    )

    model_config = ConfigDict(from_attributes=True)


class BlogGenerationJobResponse(BaseModel):
    """Response schema for a blog generation job status.

    Provides status tracking for frontend polling of blog generation jobs.

    Attributes:
        id: Unique job identifier.
        jurisdiction_id: Jurisdiction the generation is for.
        status: Current job status (PENDING, IN_PROGRESS, COMPLETED, FAILED).
        error_message: Error details if job failed.
        created_at: Job creation timestamp.
        started_at: When the job started processing.
        completed_at: When the job finished (success or failure).
        triggered_by: User ID who triggered the generation.

    Examples:
        >>> response = BlogGenerationJobResponse.model_validate(job)
    """

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    jurisdiction_id: UUID
    status: str = Field(description="Current job status")
    error_message: Optional[str] = Field(default=None, description="Error details on failure")
    created_at: datetime = Field(description="Job creation timestamp")
    started_at: Optional[datetime] = Field(default=None, description="Job start timestamp")
    completed_at: Optional[datetime] = Field(default=None, description="Job completion timestamp")
    triggered_by: Optional[UUID] = Field(
        default=None, description="User ID who triggered generation"
    )


class BlogGenerationTriggerResponse(BaseModel):
    """Response schema after triggering blog generation.

    Returns the job ID for status polling.

    Attributes:
        job_id: Job ID for polling status.
        jurisdiction_id: Jurisdiction being generated for.
        status: Initial job status (PENDING).
        message: User-friendly status message.

    Examples:
        >>> response = BlogGenerationTriggerResponse(
        ...     job_id=job.id,
        ...     jurisdiction_id=jur_id,
        ...     status="PENDING",
        ...     message="Blog generation job queued"
        ... )
    """

    job_id: UUID = Field(description="Job ID for polling status")
    jurisdiction_id: UUID = Field(description="Jurisdiction being generated for")
    status: str = Field(description="Initial job status (PENDING)")
    message: str = Field(
        default="Blog generation job queued successfully",
        description="User-friendly status message",
    )


class ProjectBulkBlogJobItemResponse(BaseModel):
    """Response schema for a single item within a bulk blog generation job.

    Attributes:
        jurisdiction_id: Jurisdiction being generated for.
        status: Individual item result (success, failed, skipped).
        message: Human-readable status message for this item.
        public_url: Public URL if the item was published, else None.
    """

    jurisdiction_id: UUID
    status: str
    message: str
    public_url: Optional[str] = None


class ProjectBulkBlogJobResponse(BaseModel):
    """Response schema for a project-level bulk blog generation job.

    Provides status tracking for frontend polling of bulk generation jobs,
    including aggregate counts and per-item outcomes.

    Attributes:
        id: Unique job identifier.
        project_id: Project the bulk generation is for.
        status: Current job status (PENDING, IN_PROGRESS, COMPLETED, COMPLETED_WITH_ERRORS, FAILED).
        totals: Total jurisdictions to process.
        processed: Number successfully processed.
        failed: Number failed.
        skipped: Number skipped (hash unchanged or placeholder).
        publish_requested: Whether to publish posts after generation.
        error_summary: High-level error summary if applicable.
        created_at: Job creation timestamp.
        started_at: When the job started processing.
        completed_at: When the job finished (success or failure).
        triggered_by: User ID who triggered the generation.
        items: List of individual item outcomes (populated when checking status).
    """

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    project_id: UUID
    status: str = Field(description="Current bulk job status")
    totals: int
    processed: int
    failed: int
    skipped: int
    publish_requested: bool
    error_summary: Optional[str] = Field(default=None, description="Error summary on failure")
    created_at: datetime
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    triggered_by: Optional[UUID] = None

    # Ad-hoc aggregation of items
    items: List[ProjectBulkBlogJobItemResponse] = Field(default_factory=list)
