"""Jurisdiction Blog Post models for domain-agnostic blog generation.

This model stores auto-generated SEO-friendly blog posts from the Jurisdiction State
(Compliance Ledger). Blog content is tailored to the organization's industry and
project context, without any hardcoded domain assumptions.

Content is stored in two formats:
- content: raw Markdown (source of truth for regeneration)
- content_html: pre-rendered HTML body (delivery format, generated at write time)

Breadcrumbs are precomputed at generation time for fast SEO markup rendering.
"""

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Dict, List, Optional
from uuid import UUID, uuid4

from sqlalchemy import JSON, Column, DateTime, String, Text, UniqueConstraint
from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from app.api.modules.v1.jurisdictions.models.jurisdiction_model import Jurisdiction


class JurisdictionBlogPost(SQLModel, table=True):
    """
    Auto-generated blog post from a Jurisdiction's regulatory state.

    This model stores SEO-friendly blog posts generated from JurisdictionState data.
    One blog post per jurisdiction. Content is domain-agnostic — adapts based on
    Organization.industry, Project.master_prompt, and Jurisdiction.prompt.

    Fields:
    -------
    id : UUID
        Primary key. Unique identifier for the blog post.

    jurisdiction_id : UUID
        Foreign key to the jurisdiction this blog post covers.

    content : str
        Full Markdown-formatted blog post body (source of truth).

    content_html : str
        Pre-rendered HTML body converted from `content` at generation time.
        Used for direct delivery via the public API and artifact publishing.
        Does not include the outer HTML shell (html/head/body tags).

    title : str
        SEO-friendly blog post title.

    slug : str
        URL-safe slug for the blog post (e.g., "eor-guide-california").
        Unique and indexed for routing.

    meta_description : str
        SEO meta description (120-160 characters).

    keywords : List[str]
        Array of SEO keywords for search optimization.

    breadcrumbs : List[Dict[str, str]]
        Precomputed breadcrumb trail for SEO markup.
        Each item: {"name": "Jurisdiction Name", "url": "/guides/industry/region/jurisdiction/"}
        Computed at generation time from jurisdiction hierarchy.

    is_published : bool
        Whether the blog post is publicly visible. Defaults to False.
        Set to True only after review (manual publish via PATCH endpoint).

    version : int
        Incremented each time the blog post is regenerated.
        Helps track content evolution and supports rollback if needed.

    content_hash : str
        SHA-256 hash of the formatted JurisdictionState data at generation time.
        Used for idempotency: if state hasn't changed (same hash),
        skip LLM regeneration.

    generation_model : Optional[str]
        Name of the LLM model used to generate this blog post.
        Useful for audit and debugging purposes.

    generated_at : Optional[datetime]
        Timestamp when the blog content was last generated by the LLM.
        Null for placeholder content.

    created_at : datetime
        Timestamp when the blog post was first generated.

    updated_at : datetime
        Timestamp of the latest regeneration.

    published_at : Optional[datetime]
        Timestamp when the blog post was published (is_published set to True).
        Null if never published.

    jurisdiction: Jurisdiction
        Relationship to the Jurisdiction this blog covers.
    """

    __tablename__ = "jurisdiction_blog_posts"  # type: ignore
    __table_args__ = (UniqueConstraint("jurisdiction_id", name="uq_jurisdiction_blog_post"),)

    id: UUID = Field(default_factory=uuid4, primary_key=True, index=True)
    jurisdiction_id: UUID = Field(
        foreign_key="jurisdictions.id",
        index=True,
        nullable=False,
        ondelete="CASCADE",
    )
    content: str = Field(sa_column=Column(Text, nullable=False))
    content_html: str = Field(sa_column=Column(Text, nullable=False), default="")
    title: str = Field(max_length=255, nullable=False)
    slug: str = Field(max_length=255, nullable=False, unique=True, index=True)
    meta_description: str = Field(max_length=160, nullable=False)
    keywords: List[str] = Field(default_factory=list, sa_column=Column(JSON))
    breadcrumbs: List[Dict[str, str]] = Field(
        default_factory=list,
        sa_column=Column(JSON),
        description="Precomputed breadcrumb trail: [dict(name=str, url=str), ...]",
    )
    is_published: bool = Field(default=False, nullable=False)
    version: int = Field(default=1, nullable=False)
    content_hash: str = Field(nullable=False, index=True)
    generation_model: Optional[str] = Field(default=None, max_length=255)
    generated_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True)),
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    published_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True)),
    )

    # Relationship
    jurisdiction: "Jurisdiction" = Relationship(
        back_populates="blog_posts",
    )

    tokens: list["BlogPostToken"] = Relationship(back_populates="post")


class BlogPostToken(SQLModel, table=True):
    __tablename__ = "blog_post_tokens"  # type: ignore

    id: UUID = Field(default_factory=uuid4, primary_key=True, index=True)
    post_id: UUID = Field(
        foreign_key="jurisdiction_blog_posts.id",
        index=True,
        nullable=False,
        ondelete="CASCADE",
    )

    word_token: str = Field(sa_column=Column(String, nullable=False, index=True))
    field: str = Field(sa_column=Column(String, nullable=False))
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    post: Optional[JurisdictionBlogPost] = Relationship(back_populates="tokens")
